const languages = [
    { name: "English", countryCode: "US" },
    { name: "Spanish", countryCode: "ES" },
    { name: "French", countryCode: "FR" },
    { name: "Mandarin Chinese", countryCode: "CN" },
    { name: "Arabic", countryCode: "EG" },
    { name: "Hindi", countryCode: "IN" },
    { name: "Russian", countryCode: "RU" },
    { name: "Portuguese", countryCode: "BR" },
    { name: "Bengali", countryCode: "BD" },
    { name: "Urdu", countryCode: "PK" },
    { name: "German", countryCode: "DE" },
    { name: "Japanese", countryCode: "JP" },
    { name: "Punjabi", countryCode: "PK" },
    { name: "Javanese", countryCode: "ID" },
    { name: "Telugu", countryCode: "IN" },
    { name: "Wu Chinese", countryCode: "CN" },
    { name: "Korean", countryCode: "KR" },
    { name: "Marathi", countryCode: "IN" },
    { name: "Tamil", countryCode: "IN" },
    { name: "Vietnamese", countryCode: "VN" },
    { name: "Turkish", countryCode: "TR" },
    { name: "Italian", countryCode: "IT" },
    { name: "Thai", countryCode: "TH" },
    { name: "Gujarati", countryCode: "IN" },
    { name: "Jin Chinese", countryCode: "CN" },
    { name: "Southern Min Chinese", countryCode: "CN" },
    { name: "Persian", countryCode: "IR" },
    { name: "Polish", countryCode: "PL" },
    { name: "Pashto", countryCode: "AF" },
    { name: "Kannada", countryCode: "IN" },
    { name: "Xiang Chinese", countryCode: "CN" },
    { name: "Malayalam", countryCode: "IN" },
    { name: "Sundanese", countryCode: "ID" },
    { name: "Hausa", countryCode: "NG" },
    { name: "Odia", countryCode: "IN" },
    { name: "Burmese", countryCode: "MM" },
    { name: "Hakka Chinese", countryCode: "CN" },
    { name: "Ukrainian", countryCode: "UA" },
    { name: "Bhojpuri", countryCode: "IN" },
    { name: "Tagalog", countryCode: "PH" },
    { name: "Yoruba", countryCode: "NG" },
    { name: "Maithili", countryCode: "NP" },
    { name: "Uzbek", countryCode: "UZ" },
    { name: "Sindhi", countryCode: "PK" },
    { name: "Amharic", countryCode: "ET" },
    { name: "Fula", countryCode: "NG" },
    { name: "Romanian", countryCode: "RO" },
    { name: "Oromo", countryCode: "ET" },
    { name: "Igbo", countryCode: "NG" },
    { name: "Azerbaijani", countryCode: "AZ" },
    { name: "Awadhi", countryCode: "IN" },
    { name: "Gan Chinese", countryCode: "CN" },
    { name: "Cebuano", countryCode: "PH" },
    { name: "Dutch", countryCode: "NL" },
    { name: "Kurdish", countryCode: "IQ" },
    { name: "Serbo-Croatian", countryCode: "RS" },
    { name: "Malagasy", countryCode: "MG" },
    { name: "Saraiki", countryCode: "PK" },
    { name: "Nepali", countryCode: "NP" },
    { name: "Sinhalese", countryCode: "LK" },
    { name: "Chittagonian", countryCode: "BD" },
    { name: "Zhuang", countryCode: "CN" },
    { name: "Khmer", countryCode: "KH" },
    { name: "Turkmen", countryCode: "TM" },
    { name: "Assamese", countryCode: "IN" },
    { name: "Madurese", countryCode: "ID" },
    { name: "Somali", countryCode: "SO" },
    { name: "Marwari", countryCode: "IN" },
    { name: "Magahi", countryCode: "IN" },
    { name: "Haryanvi", countryCode: "IN" },
    // { name: "Hindi Belt", countryCode: "IN" },
    { name: "Hungarian", countryCode: "HU" },
    { name: "Chhattisgarhi", countryCode: "IN" },
    { name: "Greek", countryCode: "GR" },
    { name: "Chewa", countryCode: "MW" },
    { name: "Deccan", countryCode: "IN" },
    { name: "Akan", countryCode: "GH" },
    { name: "Kazakh", countryCode: "KZ" },
    { name: "Northern Min Chinese", countryCode: "CN" },
    { name: "Sylheti", countryCode: "BD" },
    { name: "Zulu", countryCode: "ZA" },
    { name: "Czech", countryCode: "CZ" },
    { name: "Kinyarwanda", countryCode: "RW" },
    { name: "Dhundhari", countryCode: "IN" },
    { name: "Haitian Creole", countryCode: "HT" },
    { name: "Eastern Min Chinese", countryCode: "CN" },
    { name: "Ilocano", countryCode: "PH" },
    { name: "Quechua", countryCode: "PE" },
    { name: "Kirundi", countryCode: "BI" },
    { name: "Swedish", countryCode: "SE" },
    { name: "Hmong", countryCode: "CN" },
    { name: "Shona", countryCode: "ZW" },
    { name: "Uyghur", countryCode: "CN" },
    { name: "Hiligaynon/Ilonggo", countryCode: "PH" },
    { name: "Mossi", countryCode: "BF" },
    { name: "Xhosa", countryCode: "ZA" },
    { name: "Belarusian", countryCode: "BY" },
    { name: "Balochi", countryCode: "PK" },
    { name: "Konkani", countryCode: "IN" },
    { name: "Kanuri", countryCode: "NG" },
    { name: "Bavarian", countryCode: "DE" },
    { name: "Burmese", countryCode: "MM" },
    { name: "Slovak", countryCode: "SK" },
    { name: "Malay", countryCode: "MY" },
    { name: "Tatar", countryCode: "RU" },
    { name: "Zaza", countryCode: "TR" },
    { name: "Sanaani Spoken Arabic", countryCode: "YE" },
    { name: "South Azerbaijani", countryCode: "IR" },
    { name: "Somali", countryCode: "SO" },
    { name: "Bosnian", countryCode: "BA" },
    { name: "Gilaki", countryCode: "IR" },
    { name: "Karakalpak", countryCode: "UZ" },
    { name: "Tigrinya", countryCode: "ER" },
    { name: "Rundi", countryCode: "BI" },
    { name: "Eastern Min Chinese", countryCode: "CN" },
    { name: "Maay", countryCode: "SO" },
    { name: "Kurdish", countryCode: "TR" },
    { name: "Nigerian Fulfulde", countryCode: "NG" },
    { name: "Serbian", countryCode: "RS" },
    { name: "Uzbek", countryCode: "UZ" },
    { name: "Bhojpuri", countryCode: "IN" }
];

export default languages;
